### ISSUE TITLE
ImportError: No module named 'cortexutils' on V2.0.4

### ISSUE THREAD

**Issue by mathurin68** [TheHive-Project/Cortex#102]
ImportError: No module named 'cortexutils'   errors in Cortex. 

Most of the modules seem to be working but some give this error - 
ImportError: No module named 'cortexutils'

[ip] 185[.]141[.]25[.]242
Analyzer: Onyphe_Forward_1_0 Date: 4 minutes ago 
Invalid output
Traceback (most recent call last):
  File "Onyphe/onyphe_analyzer.py", line 3, in <module>
    from cortexutils.analyzer import Analyzer
ImportError: No module named 'cortexutils'

### Work Environment
Ubuntu 16.04 LTS 
Version 2.0.4
Installed from apt

**Comment by 3c7** [comment]
Hello @mathurin68, as some analyzers rely on python 2 while other do on python 3, you need to install cortexutils for both, python 2 and python 3.

**Comment by 3c7** [comment]
See also: https://github.com/TheHive-Project/CortexDocs/blob/master/installation/analyzers.md#installation
