### ISSUE TITLE
Automatic observables extraction from analysis reports.

### ISSUE THREAD

**Issue by thevidocq** [TheHive-Project/Cortex#111]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type
Question :)

### Work Environment
Ubuntu 16.04 / TheHive:
TheHive3.0.10
Elastic4Play1.4.6
Play2.6.7
Elastic4s5.6.0
ElasticSearch5.6.2

Ubuntu16.04/Cortex:
Cortex2.0.4
Elastic4Play1.5.0
Play2.6.12
Elastic4s5.6.0
ElasticSearch client5.6.2
ElasticSearch cluster5.6.9

### Problem Description
On analyzer configuration (es: cuckoo /fileinfo/msgparser) I have set TRUE the parameter "Extract observables" (Set to True to enable automatic observables extraction from analysis reports.)

But when the analysis finish I cannot see nothing about automatic extraction on TheHive case. I don't know if this behavior is expected or is a misconfiguration. Can you help me? How this feature work? Thanks.

**Comment by obikao** [comment]
I'm experiencing this issue as well.

The analyzers are set to extract observables but do not show up in the Hive case

**Comment by saadkadhi** [comment]
When you enable observable extraction, the analyzers will try to figure out elements that look like observables in the results and add them to the resulting report. It uses `ioc-parser` and is prone to a lot of FPs (we have ideas to drop the number of FPs in the future).

As such, the extracted `observables` will be in the raw report that you can view in TheHive or in Cortex. However, this does not mean that TheHive will automatically add those potential observables to the case.

You are probably looking for TheHive-Project/TheHive#209 which should be included in TheHive 3.1 (end of July).

**Comment by 3c7** [comment]
Remark: not `ioc-parser` but a selfmade regex-based extractor, because ioc-parser depends on some python 2 modules.

**Comment by obikao** [comment]
Additional Info:

I'd like to continue using  Robtex_Reverse_PDNS_Query_1_0 plugin as an example. When viewing the data in the hive via the Raw Report function, it is only showing the "full" portion of the data structure (where the full data structure includes ['summary', 'full', 'success', 'artifacts'] as top level keys). I am assuming 'artifacts' is the key for the automatic observable extraction.

**Comment by 3c7** [comment]
Yes, you're right. `artifacts` is the key used for automatic observable extraction. E.g. MISP uses it for receiving results from Cortex. Currently it is not possible to use the `artifacts`-part in TheHive itself. The adding of new observables through analyzer should be implemented in TheHive v3.1, as @saadkadhi said.

**Comment by obikao** [comment]
@thevidocq (or anyone that comes across this thread in the future) A hack for now is to do the following:

in TheHive/thehive-cortex/app/connectors/cortex/services/CortexSrv.scala change line 280 from
`              case _          ⇒`
to
`              case _          ⇒ s'/path/to/a/python/script $cortexJobId $jobId'`

you can then write a quick script like so:

`import sys
import time
from elasticsearch import Elasticsearch
from cortex4py.api import Api
from cortex4py.query import *
from thehive4py.api import TheHiveApi
from thehive4py.models import CaseObservable


cortexJobId = sys.argv[1]
jobId = sys.argv[2]

es = Elasticsearch(['127.0.0.1'], port=9200)
api = Api(<URL FOR CORTEX>, <CORTEX API KEY>)

hive_api = TheHiveApi(<URL FOR HIVE>, <HIVE API KEY>)


artifacts = self.api.jobs.get_artifacts(cortexJobId)
if artifacts:
	caseId = self.es.search(index='the_hive_13', body={'query':{'match':{'objectId': jobId,}}})['hits']['hits'][0]['_source']['rootId']

	for a in artifacts:
		ob = CaseObservable(dataType=a.dataType, data=a.data)
		self.hive_api.create_case_observable(caseId, ob)
		time.sleep(1)`

There isn't any sort of error checking, objects, etc. and it's inefficient as hell but it should get you started down a decent path
