### ISSUE TITLE
Refreshing analyzers does not refresh definition if already defined

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/Cortex#115]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| Cortex version / git hash   | 2.0.4
| Package Type              | DEB

### Problem Description
I just upgraded the cortex analyzers from the Github repository (master branch), mainly to be able to use the VirusTotal GetReport analyzer on URL. Unfortunately, Cortex does not detect this analyzer is now available for URL.
I refreshed the analyzer list by clicking on the "Refresh analyzers" on the "Organization > Analyzers" menu and by restarting Cortex.

### Steps to Reproduce
1. Upgrade analyzers with one definition file modified
2. Refresh analyzers in Cortex UI
3. Definition of  the analyzer does not change (but it should)

**Comment by nadouani** [comment]
Hello,

this is in fact expected. Refreshing the analyzers using the `Refresh analyzers` button, will just refresh the collection of analyzer definitions, not of the already enabled analyzers.

So, you can just disable and re-enable the VT analyzer.
