### ISSUE TITLE
Analyzers filter in Jobs History view is limited to 25 analyzers

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/Cortex#116]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| Cortex version / git hash   | 2.0.4
| Package Type              | DEB

### Problem Description
I have 29 analyzers defined on my Cortex instance but only 25 of them are displayed in the available filter in the Jobs History view

### Steps to Reproduce
1. Enable 26 analyzers or more
2. Go to Jobs History view
3. Deploy the "Analyzers" filter
4. Some of the analyzers are not available for filtering

### Complementary information

Analyzers configured in my Cortex instance:
![capture1](https://user-images.githubusercontent.com/3243772/42748795-bdd06c10-88e1-11e8-8feb-ab91c106e655.PNG)

Analyzers available in Jobs History filter:
![capture0](https://user-images.githubusercontent.com/3243772/42748820-cd6e25fe-88e1-11e8-97ac-863565c24841.PNG)

**Comment by nadouani** [comment]
Well, the dropdown component does in fact limit the items to 25 by default
