### ISSUE TITLE
Cortex silently closes connection on long running waitReport function

### ISSUE THREAD

**Issue by ilyaglow** [TheHive-Project/Cortex#122]
### Request Type
Questionable bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Cortex version / git hash   | 2.1.0-0.1RC1
| Package Type              | Docker

### Problem Description
Honestly, I'm not sure if it's even a bug or an example of a wrong usage, but function `waitReport` doesn't work as expected for long running analysers, because of [Play Framework internal timeouts](https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play-akka-http-server/src/main/resources/reference.conf#L16-L19).

### Steps to Reproduce
1. Add an analyser that runs longer than 75 seconds.
2. Create a job with it and start waiting for a report with `atMost` parameter longer than 75 seconds.
3. The connection to Cortex will be closed after 75 seconds, leaving someone who waits for the report with undefined job status.

### Possible Solutions
As a work around we added timeout values that fit us well to our `application.conf`:
```
play.server.http.idleTimeout = 300s
play.server.akka.requestTimeout = 300s
```

Or does it work as intended and the user should just make another poll request with the same `atMost` parameter after a minute or so?

**Comment by To-om** [comment]
Timeouts cannot be changed for a particular request. When internal timeout occurs, Play (akka in fact) closes the connection. Timeout should be set to the highest acceptable value of `atMost`.
If the timeout is high enough and the report is not available yet after `atMost` duration, Cortex returns the job data with `InProgress` status. The client should rerun its query.
