### ISSUE TITLE
Show PAP value in the Org > Analyzers screen

### ISSUE THREAD

**Issue by saadkadhi** [TheHive-Project/Cortex#124]
### Request Type
Enhancement

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Cortex version / git hash   | 2.1.0-RC1

### Problem Description
The Max PAP value should be displayed in the *Org > Analyzers* screen like the Max TLP value.

**Comment by nadouani** [comment]
Responders admin page has also been updated to display the PAP config
