### ISSUE TITLE
Yara analyzer configuration dialog broken

### ISSUE THREAD

**Issue by ecapuano** [TheHive-Project/Cortex#134]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16
| OS version (client)       |  MacOS
| Cortex version / git hash   | 2.1.0
| Package Type              | DEB from repo
| Browser type & version    | If applicable

### Problem Description
Describe the problem/bug as clearly as possible.

### Steps to Reproduce
1. Attempting to edit the Yara_2_0 analyzer produces a configuration window that cannot be edited and contains the default path split across many entries.

![](https://puu.sh/BB0lO/aca87b10cf.png)
I've tried to delete the multi-line entries to add the correct entry, but it will not allow me to edit or delete them.

**Comment by ecapuano** [comment]
Also fails to enable by leaving default configuration "as-is"

**Comment by ecapuano** [comment]
Should've mentioned, this is with *today's* version of Cortex & Cortex-Analyzers

**Comment by nadouani** [comment]
Hi @ecapuano I'll take a look on this. AFAIK, I've already seen and fixed this issue. ping @3c7

**Comment by nadouani** [comment]
@ecapuano is it possible to know when you did enable the Yara analyzer? I mean, before or after https://github.com/TheHive-Project/Cortex-Analyzers/issues/245 ?

Try to disable and re-enable it. It's probably because the analyzer has been enabled before the fix of the issue identified above.
