### ISSUE TITLE
Display analyzers only if necessary configuration values are set

### ISSUE THREAD

**Issue by 3c7** [TheHive-Project/Cortex#14]
### Request Type
FR

### Idea
If necessary data the analyzer needs such as username, password or an api key are defined through a config file (the json file or so...), the analyzer should only be displayed if all as required marked config values are set.

Maybe this is something to consider together with
- https://github.com/CERT-BDF/Cortex-Analyzers/issues/33
- https://github.com/CERT-BDF/Cortex-Analyzers/issues/32

From my point of view, this is cortex sided so I added the issue here.

**Comment by nadouani** [comment]
Thanks @3c7 yes this is a Cortex thing so here is the right place to track the fix.

**Comment by nadouani** [comment]
We just need to add a validation step when reading the JSON files describing analyzers.

**Comment by nadouani** [comment]
This will be invalid with Cortex 2, since the users will be able to enable the desired analyzers from the UI.
