### ISSUE TITLE
Running Cortex analyzers from Python or Scala code (without installing Cortex)

### ISSUE THREAD

**Issue by veeral-patel** [TheHive-Project/Cortex#150]
First of all, I really appreciate everyone's unpaid, hard work in creating TheHive for us. 

I was wondering if it's possible to run Cortex analyzers from Python or Scala code. I know I can use the REST API, but I just want to run analyzers in a few scripts, and don't want to set up Cortex.

Something like this:

```
from cortex import run_analyzer

run_analyzer('VirusTotal.scan_url', inputs={
    "url": "http://www.google.com"
}
```

Thank you!

**Comment by nadouani** [comment]
Hello @veeral-patel Thanks for your support.

I think this is more a question than an issue, and I suggest to discuss it on the [Gitter channel](https://gitter.im/TheHive-Project/TheHive), so that you can have more users giving answers.

That said, the analyzers are simple python scripts that you can call by passing the JSON input via the standard input.

Thanks

**Comment by veeral-patel** [comment]
I asked on Gitter yesterday but no one replied. Asked again.

Do you have an example of calling an analyzer?

**Comment by 3c7** [comment]
As you the Input of Analyzers is passed via stdin and they return the results via stdout (both as json), you could call them theoretically via subprocess functions, like you call other external programs in python. From the bash, you'd call an analyzer like that:
`echo '{"dataType": "domain", "data": "google.de"}' | ./analyzer.py` or `./analyzer.py <<< '{"dataType": "domain", "data": "google.de"}'`
If the analyzer needs configuration variables, you need to take care of them yourself, as there's no cortex managing that for you. Check the "How to create a cortex-analyzer" documentation to get more insights into how the analyzers work.

**Comment by veeral-patel** [comment]
I see. So I just run each analyzer with Python and pass in JSON input from `stdin`.

Is there documentation on what the input for each analyzer looks like? For example, where would I find example JSON I can pass into the VirusTotal analyzer?

**Comment by 3c7** [comment]
Beside `dataType` and `data` there is a `config` object, the containig values can be obtained from the analyzer definition file (the `.json` files that came along with the analyzer).

**Comment by veeral-patel** [comment]
For VirusTotal, for example, where would I add my API key so the analyzer can use it?

**Comment by 3c7** [comment]
See https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md#virustotal, you have to put it into `config: {key: ...}`.
