### ISSUE TITLE
thehiveproject/thehive:latest

### ISSUE THREAD

**Issue by bsploit** [TheHive-Project/Cortex#154]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| Cortex version / git hash   | 2.1.2
| Package Type              | Docker thehiveproject/thehive:latest

### Steps to Reproduce
1. Create case with russian letters in Title or description in TheHive
2. launch Mailer Responder from case menu
3. Cortex shows following error for mailer responder
Invalid output
Traceback (most recent call last):
  File "Mailer/mailer.py", line 59, in <module>
    Mailer().run()
  File "Mailer/mailer.py", line 47, in run
    msg.attach(MIMEText(description, 'plain'))
  File "/usr/lib/python2.7/email/mime/text.py", line 30, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python2.7/email/message.py", line 226, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python2.7/email/message.py", line 262, in set_charset
    self._payload = self._payload.encode(charset.output_charset)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

### Possible Solutions
in mailer.py do encode('utf-8') of title and description

title = self.get_param('data.title', None, 'title is missing')
**title=title.encode('utf-8')**
description = self.get_param('data.description', None, 'description is missing')
**description=description.encode('utf-8')**

**Comment by nadouani** [comment]
Moving this to Cortex-Analyzers repository
