### ISSUE TITLE
Unable to disable invalid responders

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex#157]
### Request Type
Bug

### Problem Description
Invalid responders are responders that have been enabled, and for which the definition has been changed, making them obsolete.

The responders administration page is supposed to list them, allowing administrators to delete them.
 
![screen shot 2018-12-17 at 11 42 56](https://user-images.githubusercontent.com/21827/50083226-5c603380-01f3-11e9-8f79-d6f7a05a9b75.png)

**Comment by nadouani** [comment]
If you cannot wait for this fix, you can list all your enabled responders

```
curl 'http://localhost:9200/cortex_2/worker/_search?q=type:responder'
```

find the one you want to delete, and then 

```
curl -XDELETE 'http://localhost:9200/cortex_2/worker/RESPONDER_ID'
```

**Comment by cyberpescadito** [comment]
A year later.. :) 
I have a dead responder still showing in responder menu & in thehive dropdown list of responders.

ElasticSearch version:
```
  "version" : {
    "number" : "5.6.16",
    "build_hash" : "3a740d1",
    "build_date" : "2019-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  }
```
command:
`curl 'http://127.0.0.1:9200/cortex_1_4/worker/_search?q=type:responder'`

result:
`{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}`

I can't get the responder ID this way. any clue? 
many thanks

**Comment by Pindinga1** [comment]
For delete responder
http://localhost:9001/api/responder <--- GET ID RESPONDER TO DELETE

curl -XDELETE -H 'Authorization: Bearer **API_KEY**' 'https://localhost:9001/api/organization/RESPONDER_ID'
