### ISSUE TITLE
Support for AddTagToAlert

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/Cortex#173]
### Request Type
Feature-Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 8
| Cortex version / git hash   | 2.1.3
| Package Type              | DEB

### Problem Description
I want to add a tag to the alert (that later could potentially get a case).
Unforunately there is no AddTagToAlert function, only AddTagToCase or Observable exists.

**Comment by nadouani** [comment]
This needs to be made in TheHive not Cortex :)

Can you please copy this issue in TheHive repo? Thanks
