### ISSUE TITLE
Error when trying to edit or disable any enabled analyser

### ISSUE THREAD

**Issue by k41zen** [TheHive-Project/Cortex#189]
When attempting to edit or disable and already enabled analyzer I'm faced with the problem described below.

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Win10 x64
| Cortex version / git hash   | 2.1.3-1
| Package Type              | Binary
| Browser type & version    | N/A

### Problem Description
Managed to enable and edit the Nessus analyzer without issues. But wanted to edit it. Now when I try to edit I get the error "Failed to edit the analyzer". When I try to delete it I get "unable to delete the analyzer".

### Steps to Reproduce
Click edit on the already enabled analyzer. Make a change and click Save. Or Click disable on the enabled analyzer.

**Comment by nadouani** [comment]
Hello, can you give us more details, if you have some logs from /var/log/cortex/application.log file?

Thanks

**Comment by k41zen** [comment]
Thanks for the reply. The only errors I get at the time of hitting the disable button are that the Org Admin account I've logged on to doesn't exist in LDAP (which is correct as it's a generic account).

**Comment by nadouani** [comment]
do you have an client side error? Do you see something on the browser developper console?

**Comment by k41zen** [comment]
ah cool. I'd hardened Nginx and don't allow the DELETE method so getting a 405. Thanks so much for the speedy response. Will change that now.

**Comment by nadouani** [comment]
OK, no problem
