### ISSUE TITLE
No module named cortexutils with python3

### ISSUE THREAD

**Issue by mathgirl26** [TheHive-Project/Cortex#192]
Hi,

I have an issue with RecordedFuture analyzer:
"errorMessage": "Invalid output\nTraceback (most recent call last):\n  
  File \"RecordedFuture/recordedfuture.py\", line 4, in <module>\n    
  from cortexutils.analyzer import Analyzer\nModuleNotFoundError: No module named 'cortexutils'\n",

I think the problem is "#!/usr/bin/env python3".
<img width="222" alt="issue-cortex" src="https://user-images.githubusercontent.com/25195782/58008985-c4da7600-7aed-11e9-8d7f-ad8519e5cb82.PNG">

As you can see in this picture, cortexutils is found in the file "/usr/lib/**python2.7**/site-packages/cortexutils/__init__.py"

It sould be also find in pyhton3x. So do you know how to solve that?

Thank you in advance for your help.

_Originally posted by @mathgirl26 in https://github.com/TheHive-Project/Cortex/issues/34#issuecomment-493898511_

**Comment by nadouani** [comment]
Hello @mathgirl26 most of the analyzer use Python 3, some of them are still using Python2 (because if unavailable dependencies compatible with Python3).

You need to have `cortexutils` installed for both Python2 and Python3

Thanks
