### ISSUE TITLE
Cortex unable to connect to AWS Elasticsearch service (version 5.6)

### ISSUE THREAD

**Issue by vtomardb** [TheHive-Project/Cortex#196]
I am running Elasticsearch 5.6 as AWS hosted service and running cortex from ECS.

### Request Type
Bug

### Problem Description
If I use EC2 hosted elasticsearch or docker based it works but if I use AWS hosted ElasticSearch Service it is not able to connected, error: `elasticsearch host not configured`

### Steps to Reproduce
Try connecting to AWS hosted service

### Possible Solutions
(keep this section if you have suggestions on how to solve the problem. **Otherwise delete it**)

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by To-om** [comment]
When the Cortex container is started, it tries to find the elasticsearch instance by resolving the name `elasticsearch`. This works with a docker-compose but not in your configuration. In your case, you must configure the elasticsearch host by adding the parameter `--es-hostname ip-or-hostname-of-es` when you start the container. You can also bind your configuration file.
