### ISSUE TITLE
Cortex 3.0.0-RC3 tries to connect to wrong index

### ISSUE THREAD

**Issue by runninbutt** [TheHive-Project/Cortex#197]
# When upgrading from 3.0.0-RC2 to RC3 can't connect to index

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| Cortex version / git hash   | 3.0.0-RC3
| Package Type              | Docker
| Browser type & version    | Not relevant

### Problem Description
I have a separate ElasticSearch 5.6.16. I upgraded from 2.x to 3.0.0-RC2 and everything worked fine. I upgraded from 3.0.0-RC3, made the required changes to application.conf but my Cortex can't connect to Elastic. It tries to poll index cortex_4? My understanding is that it should be cortex_3 as described in [CortexDocs](https://github.com/TheHive-Project/CortexDocs/blob/master/admin/schema_version.md).
Documentation is quite vague: how do i define that URI syntax (cluster.name etc.) when connecting to Elastic? Or do i need to define the cluster.name?

[error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_4/_search?scroll=60000ms
StringEntity({"version":"true","query":{"bool":{"must":[{"term":{"relations":{"value":"user"}}},{"term":{"status":{"value":"Ok"}}}]}},"from":0,"sort":[{"_id":{"order":"desc"}}]},Some(application/json))
 => ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,null,None)),None)

My ElasticSearch configuration in application.conf:
```hocon
search {
  # Name of the index
  # Name of the Elasticsearch cluster
  #cluster = hive
  # Address of the Elasticsearch instance
  uri = "http://elastic.domain.local:9200"
  # Scroll keepalive
  keepalive = 1m
  # Size of the page for scroll
  pagesize = 50
  # Number of shards
  nbshards = 5
  # Number of replicas
  nbreplicas = 1
  # Arbitrary settings
  settings {
    # Maximum number of nested fields
    mapping.nested_fields.limit = 100
  }

  ### XPack SSL configuration
  # Username for XPack authentication
  #search.username
  # Password for XPack authentication
  #search.password
  # Enable SSL to connect to ElasticSearch
  search.ssl.enabled = false
  # Path to certificate authority file
  #search.ssl.ca
  # Path to certificate file
  #search.ssl.certificate
  # Path to key file
  #search.ssl.key

  ### SearchGuard configuration
  # Path to JKS file containing client certificate
  #search.guard.keyStore.path
  # Password of the keystore
  #search.guard.keyStore.password
  # Path to JKS file containing certificate authorities
  #search.guard.trustStore.path
  ## Password of the truststore
  #search.guard.trustStore.password
  # Enforce hostname verification
  #search.guard.hostVerification
  # If hostname verification is enabled specify if hostname should be resolved
  #search.guard.hostVerificationResolveHostname
}
```

### Steps to Reproduce
1. Upgrade docker image from 3.0.0-RC2 to RC3
2. Make the changes to application.conf
3. Try to start docker instance

### Possible Solutions
Shouldn't the elastic component reference cortex_3? Or atleast connect first to cortex_3 and then suggest upgrade.

### Complementary information
(add anything that can help identifying the problem such as **log** excerpts, **screenshots**, **configuration dumps** etc.)

**Comment by b00lpy** [comment]
Running this from Windows host works fine, but on Ubuntu Server 18.04 I've got the same error.
![cortexerr](https://user-images.githubusercontent.com/50588190/60505267-ac9c7000-9cc3-11e9-8e33-0e1a644721c5.PNG)

**Comment by To-om** [comment]
Cortex 3.0.0-RC3 adds support of Elasticsearch 6 and needs a database migration. So the version 3.0.0-RC3 uses the index "cortex_4" (I've updated the documentation). When the index is not found, Cortex should ask you to update the database. Is it the case ?

Cluster name in configuration is not useful when http is used to connect to Elasticsearch.

**Comment by b00lpy** [comment]
@To-om I'm building the environment right now, so I'm not performing a migration but just starting using this version for the first time.
Actually everything works ( not tested every features, but it seems the main are working fine ) but i see some random errors/warning which are weird and I can't honestly explain. Are these bugs of this intermediary version?

**Comment by runninbutt** [comment]
@To-om Yeah, the case was updating the DB to a newer version. Case closed now that the documentation has been updated.
