### ISSUE TITLE
Login error after Cortex upgrade to 3

### ISSUE THREAD

**Issue by lokuhetty** [TheHive-Project/Cortex#199]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)      | CentOS Linux release 7.6.1810
| Cortex version              |cortex-3.0.0-0.1RC3
| Package Type              | RPM
| Elasticsearch Version   | 5.6

### Problem Description
I just upgraded the Cortex 2.X to 3.0 via stable channel RPM. Installation didn't change the configuration automatically. So I added the URI instead of the HOST and added the cluster as a new section. Now the Cortex starts up.
My URI line : uri = "http://127.0.0.1:9200"  (I have change the port to 9200 from 9300)

Now when I try to log in , I get "Authentication Failure". Note that my username goes like an email address. (dasun@fincsirt.lk)

![image](https://user-images.githubusercontent.com/2539152/59492764-459b5080-8ea7-11e9-8c73-dcbfa7637880.png)

And the with the error, "@"sign in the username feild gets deleted as in the above image. I have queried the Elasticsearch for the user and it still shows the username with the charachter "@" shown below

![image](https://user-images.githubusercontent.com/2539152/59492901-99a63500-8ea7-11e9-9e4e-0e97d874c456.png)

Following is a screen of the indices that I have. I have thehive in here as well and the same username was there and it still works after upgrading. 

![image](https://user-images.githubusercontent.com/2539152/59492981-c3f7f280-8ea7-11e9-8566-9b560940cad8.png)

**Comment by nicpenning** [comment]
I can confirm this as well. Using local or AD auth and having a username such as "user1234" the user fails to login and in the user field it shows "user 1234" with a space. In the logs it appears to try and login with the wrong account "user 1234". Tested on Cortex 3 RC-3, Ubuntu 18, ES 5.6. TheHive works great after upgrade to 3.4.0-RC1 with same auth settings.

**Comment by nadouani** [comment]
Thanks to the `lowerCase` function of Lodash (https://lodash.com/docs/4.17.11#lowerCase) and my bad for not reading the full method description. It replaces non alpha chars to `space` :)

**Comment by nadouani** [comment]
The `lowerCase` function is in fact doing this

> Converts string, as space separated words, to lower case.

**Comment by nicpenning** [comment]
Thanks for addressing this!
