### ISSUE TITLE
Issue building from source

### ISSUE THREAD

**Issue by dhersh2** [TheHive-Project/Cortex#202]
# EDIT THIS TITLE BEFORE POSTING. Use this template for bug reports. If you'd like to request a feature, please be as descriptive as possible and delete the template except the first section (Request Type)

### Request Type

Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | 7
| Cortex version / git hash   |3.0.0-RC3-0-g13ecd33
| Package Type              |  From source
| Browser type & version    |Chrome

### Problem Description
When trying to run ./sbt clean stage from within the Cortex project I receive the following errors. My npm is current and so is node.js. I have also tried to build just the UI portion of cortex and get the same error by going into Cortex/www and running npm install --ignore-scripts and npm run build. 

The backend is build correctly however when i run cortex from the command line it starts up but when I navigate to the page I get error GET/index. Thus it is definitely the UI portion not building correctly. I have tried running as none root as well as root. 

[error] npm ERR! Linux 3.10.0-957.el7.x86_64
[error] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
[error] npm ERR! node v6.16.0
[error] npm ERR! npm  v3.10.10
[error] npm ERR! code ELIFECYCLE
[error] npm ERR! cortex@3.0.0-RC3 build: `cross-env NODE_ENV=production webpack -p --colors`
[error] npm ERR! Exit status 2
[error] npm ERR!
[error] npm ERR! Failed at the cortex@3.0.0-RC3 build script 'cross-env NODE_ENV=production webpack -p --colors'.
[error] npm ERR! Make sure you have the latest version of node.js and npm installed.
[error] npm ERR! If you do, this is most likely a problem with the cortex package,
[error] npm ERR! not with npm itself.
[error] npm ERR! Tell the author that this fails on your system:
[error] npm ERR!     cross-env NODE_ENV=production webpack -p --colors
[error] npm ERR! You can get information on how to open an issue for this project with:
[error] npm ERR!     npm bugs cortex
[error] npm ERR! Or if that isn't available, you can get their info via:
[error] npm ERR!     npm owner ls cortex
[error] npm ERR! There is likely additional logging output above.
[error] npm ERR! Please include the following file with any support request:
[error] npm ERR!     Cortex/www/npm-debug.log
[info] Packaging Cortex/target/scala-2.12/cortex_2.12-3.0.0-RC3-web-assets.jar ...
[info] Done packaging.
[success] Total time: 184 s, completed Jun 26, 2019 9:59:54 AM

### Complementary information
I also get additional errors further up in the UI build 
/Cortex/www/src&sourceMap!./node_modules/postcss-loader!./node_modules/sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true!./src/app/core/directives/tlp/tlp.scss 2.31 kB {0} [not cacheable] [built] [failed] [1 error]

/Cortex/www/src&sourceMap!./node_modules/postcss-loader!./node_modules/sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true!./src/app/core/directives/tlp/tlp.scss
[info]     Module build failed: Error: ENOENT: no such file or directory, scandir 
/Cortex/www/node_modules/node-sass/vendor'
[info]         at Error (native)
[info]         at Object.fs.readdirSync (fs.js:961:18)
[info]         at Object.getInstalledBinaries

**Comment by nadouani** [comment]
Hello, this is really an issue related to your dev environment, we cannot investigate and troubleshoot it. Use a recent Node version, remove your `node_modules` folder and `npm install` again
