### ISSUE TITLE
docker version of cortex breaks when you don't create a user immediately

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/Cortex#204]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | -
| Cortex version / git hash   | latest from dockerhub
| Package Type              | Docker
| Browser type & version    | -

### Problem Description
When you don't create a user on the first try, cortex displays only a white page and red "Error: user init not found" messages.

### Steps to Reproduce
1. Download docker-compose file from official docs, apply fix for #203 
2. `docker-compose up`
3. Wait until elastic and cortex have started
4. Open `localhost:9001` in your browser, click "Update Database", wait
5. Don't create a user in the form, open `localhost:9001` again

### Complementary information
[docker-compose output](https://pastebin.com/raw/uSHib2iD)

**Comment by To-om** [comment]
The issue is solved by thehive-project/elastic4play#90
