### ISSUE TITLE
docker version of cortex prints a lot of errors for auth failures

### ISSUE THREAD

**Issue by Trolldemorted** [TheHive-Project/Cortex#205]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | -
| OS version (client)       | -
| Cortex version / git hash   | latest on dockerhub
| Package Type              | Docker
| Browser type & version    | -

### Problem Description
Cortex throws errors ("Authentication failure") and warnings ("cookie has an invalid signature") often, even if no users type invalid passwords. Either those things shouldn't happen during normal usage, or it should be an error.

### Steps to Reproduce
1. Download docker-compose file from official docs, apply fix for #203 
2. `docker-compose up`
3. Wait until elastic and cortex have started
4. Open localhost:9001 in your browser, click "Update Database", wait
5. Register a user immediately to prevent #204 
6. Open some tabs, wait a while

### Complementary information
[docker-compose output](http://pastebin.com/raw/7NYpja7B)

**Comment by b00lpy** [comment]
I've got the same problem but it seems not to be an actual problem, i mean, I can log in. Probably there's something bad goin on logging level, maybe they wrote a wrong check?
I'm following that.

**Comment by To-om** [comment]
Unless you set a secret in docker compose file, the key used to sign the session cookie change at each startup. This can be the cause of your authentication problems. I advise you to update your docker-compose file with this change:
```patch
[...]
cortex:
    image: thehiveproject/cortex:latest
+  command: --secret changeme
    ports:
      - "0.0.0.0:9001:9001"
  thehive:
    image: thehiveproject/thehive:latest
+  command: --secret changeme
    depends_on:
      - elasticsearch
      - cortex
[...]
```
TheHive secret and Cortex secret don't need to be the same.
