### ISSUE TITLE
Enable responder using Cortex API

### ISSUE THREAD

**Issue by susangz** [TheHive-Project/Cortex#215]
### Request Type
Bug

### Work Environment
TheHive training VM - Beta Version

### Problem Description
I'm trying to enable/disable the Cortex Responders using the Cortex Restful API from an application I'm trying to integrate with TheHive.

It works when I use the API to enable/disable Analyzers and to disable Responders, but it doesn't seem to work to enable the Responders (or maybe I'm missing how to do it, my apologies in that case, I've searched for it in the Cortex api-doc but I haven't seen an example with responders). 

### Steps to Reproduce

1. I start enabling Responders from Cortex UI without issues and get the responders ids.

2. I remove the responder Mailer_1_0 without issues using the following command:

curl -XDELETE -H 'Authorization: Bearer 6q/NICA5aauqpqFwFJXeMWR3XIF6KC7l' 'http://localhost:9001/api/responder/c24ccf10cbbadfe4b937c4a208a59071'

3. I try to enable again that responder using the API in a similar way that enabling an analyzer including the name and the configuration:

curl -XPOST -H 'Authorization: Bearer 6q/NICA5aauqpqFwFJXeMWR3XIF6KC7l' 'http://localhost:9001/api/responder/c24ccf10cbbadfe4b937c4a208a59071' -d '{"configuration":{"from":"localhost","smtp_host":"localhost","smtp_port":25,"proxy_http":null,"proxy_https":null,"cacerts":null,"jobTimeout":30,"check_tlp":true,"max_tlp":2,"check_pap":true,"max_pap":2},"name":"Mailer_1_0"}'
A client error occurred on POST /api/responder/c24ccf10cbbadfe4b937c4a208a59071 :

**Comment by github-pba** [comment]
I get it working like this:

```
curl -s -XPOST -H "Authorization: Bearer ***KEY***" -H 'Content-Type: application/json' -d '{ "name":"Mailer_1_0", "configuration": { "from": "root@hive.comain.com", "smtp_host": "localhost", "smtp_port": 25, "proxy_http": "", "proxy_https": "", "cacerts": null, "jobTimeout": 30, "check_tlp": true, "max_tlp": 2, "check_pap": true, "max_pap": 2 }} ' http://localhost:9001/api/organization/responder/Mailer_1_0
```


Difference to yours: 
a) -H 'Content-Type: application/json'
b) URL: http://localhost:9001/api/**organization**/responder/**Mailer_1_0**
c) valid e-mail address in From field.

**Comment by susangz** [comment]
Great, it has worked!! Thanks a lot!! :-)
