### ISSUE TITLE
Error: ElasticSearch cluster is unreachable

### ISSUE THREAD

**Issue by liuxuehao** [TheHive-Project/Cortex#218]
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| Package Type              | Docker

### Problem Description
When I run ElasticSearch and Cortex in docker and access 0.0.0.0:9001 in the Chrome browser, Error: ElasticSearch cluster is unreachable in the browser

Ubuntu 16.04.3
Docker 19.03.1
Cortex: 3.0.0-RC4
Elasticsearch: 6.8.0

**Comment by github-pba** [comment]
Check the configured port numbers. If that doesn't help, post relevant config files.

**Comment by liuxuehao** [comment]
I found that using docker-compose up would pull and start two containers (cortex_cortex_1, cortex_elasticsearch_1), but cortex_elasticsearch_1 will automatically close. Is there any way to solve it?

**Comment by github-pba** [comment]
When it comes to docker, I'm away. Sorry. I don't use Docker.

**Comment by github-pba** [comment]
By the way: providing log files help supporters.

**Comment by liuxuehao** [comment]
This problem has been solved. The docker launch project will report 'elasticsearch exited with code 78'. [https://techoverflow.net/2019/03/11/how-to-fix-elasticsearch-exited-with-code-78/](url)
