### ISSUE TITLE
Fixing analyzer talosintelligence

### ISSUE THREAD

**Issue by michmich8** [TheHive-Project/Cortex#219]
Dear all,

The current analyzer of talosintelligence is not working.

### Request Type
Fixing bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat 7.6
| OS version (client)       |  Redhat 7.6
| Cortex version / git hash   | Cortex 3.0.0-RC4

### Problem Description
The current analyzer of Talosintelligence is not working due to authentication issue.

### Steps to Reproduce
1. New analyzer
1. DataType -> IP
1. Data -> enter an IP
1. Analyzer -> Select TalosReputation_1_0

Result in Cortex : Failed to query Talos details. Status_code 403

### Possible Solutions
- Add cookie to the code and modify this part of TalosReputation.py file ( ".../Cortex-Analyzers-master/analyzers/TalosReputation/TalosReputation.py)

- Here is an possible solution : 

```
data = self.get_data()
                headers={
                    'Host':'talosintelligence.com',
                    'Referer':'https://talosintelligence.com/reputation_center/lookup?search={}'.format(data),
                    'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36',
                    'Accept':'*/*',
                }

                response = requests.get('https://talosintelligence.com/sb_api/query_lookup',
                                        headers = headers,
                                        params = {
                                        'query':'/api/v2/details/ip/',
                                        'query_entry':data
                                        },
                                        )
                cookie= response.cookies

                response_details = requests.get('https://talosintelligence.com/sb_api/query_lookup',
                    headers = headers,
                    params = {
                        'query':'/api/v2/details/ip/',
                        'query_entry':data
                        },
                    cookies=cookie,
                    )

                response_location = requests.get('https://talosintelligence.com/sb_api/query_lookup',
                    headers = headers,
                    params = {
                        'query':'/api/v2/location/ip/',
                        'query_entry':data
                        },
                    cookies=cookie,
                    )
```

### Complementary information
Could you please validate this part of code and commit to the project?

Thanks for your action
Best regards

**Comment by nadouani** [comment]
Hello, can you please move this issue to Cortex-Analyzers repository? Thanks
