### ISSUE TITLE
cortex job sends 'failure' response to thehive_hooks prematurely.

### ISSUE THREAD

**Issue by BetterWorldCloud** [TheHive-Project/Cortex#224]
I launched a JoeSandbox analyzer that takes about 20 minutes to finish/gather file report. However, I noticed that theHive_hooks receives 'failure' response (for example: {'endDate': 1568134589195, 'status': 'Failure'}..........) in less than 8 minutes after JoeSandbox analyzer starts running.

Question: How can I increase cortex anaylzer's 'endDate' such that cortex job doesn't send 'failure' response to thehive_hooks prematurely.

**Comment by nadouani** [comment]
hello did you configure a timeout for your analyzer?
