### ISSUE TITLE
Run responder using API

### ISSUE THREAD

**Issue by mgabriel-silva** [TheHive-Project/Cortex#237]
### Request Type
Feature Request

### Problem Description
Cortex should have an API call to run responders, the same way there's one to run analyzers.
We got to a point when we can automatize (using hooks) some responders, but can't because there's no endpoint on the API to that.
Could it be the same call as the analyzer (/api/connector/cortex/job) but using 'responderId'?

**Comment by nadouani** [comment]
Hello, of course there is an API to call responders the same way we do for Analyzers. It's probably not documented, but it's the API that the UI is calling when you hit "run responder"

**Comment by mgabriel-silva** [comment]
Nice.
Yeah, it's not documented. I couldn't find anywhere.
What's the url?

**Comment by mgabriel-silva** [comment]
Nice.
Yeah, it's not documented. I couldn't find anywhere.
But now that you said. I've inspected the requests from thehive.
If anyone else need, it's /api/connector/cortex/action and use 'responderId'
Thank you.
