### ISSUE TITLE
Fix error message display for failed analyzers/responders

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex#243]
### Request Type
Bug

### Problem Description
In Cortex jobs list, when an anlayzer/responder fails, the error message is wrongly displayed.

**Comment by nadouani** [comment]
Use `job.errorMesage` instead of `job.message`

**Comment by dadokkio** [comment]
Hi, I think this is still an issue for responders [Version: 3.4.0-1]

When a responder fails I see a proper error in cortex response under errorMessage field:
![image](https://user-images.githubusercontent.com/355183/78758558-9a501080-797e-11ea-8358-c91f4e48930b.png)

But if I open the error in thehive it doesn't show any text:
![image](https://user-images.githubusercontent.com/355183/78758658-c23f7400-797e-11ea-81b5-fbffdc01a67b.png)

**Comment by nadouani** [comment]
Hello @dadokkio is this screenshot from TheHive or Cortex UI?

**Comment by dadokkio** [comment]
It's thehive .. I've noticed later this issue was related to cortex

**Comment by nadouani** [comment]
I think that this should be fixed in TheHive side then to display the `errorMessage` instead of `message`. I will take a look on that. Thanks

**Comment by nadouani** [comment]
Found the issue: this report dialog is not displaying the error message at all but it tries to display the report without checking the action status. I'll create an issue in TheHive for it. Thanks

**Comment by nadouani** [comment]
This issue will be solved through https://github.com/TheHive-Project/TheHive/issues/962

**Comment by dadokkio** [comment]
Thanks
