### ISSUE TITLE
Cortex Analyzers Not Found In Web UI

### ISSUE THREAD

**Issue by DevTeam34** [TheHive-Project/Cortex#249]
### Request Type
Issue

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | Ubuntu
| Cortex version / git hash   | 3.0.1-1
| Package Type              | DEB Source
| Browser type & version    | Chrome

### Problem Description

Can someone assist with this issue to. I ran all the steps according to the instructions but when log into the cortex as orgadmin i do not see the analyzers. I didnt make any changes to the file path so assuming everything is by default I would of thought the default file path to the analyzers was "/opt/Cortex-Analyzers/analyzers" but that didnt work.

I then did the troubleshooting as suggested by the community which consisted of checking the permissions and trying with and without quotes and still came up short. I then went to check the file path with the ls command and realized that path doesn't exist so I figured the i try and reinstall the cortex analyzers that states: "destination path 'Cortex-Analyzers' already exists and is not an empty directory." As the processed continued, I saw that items were getting installed to the /usr/lib/python3/dist-packages file path. So I went to check the files and saw alot of items pertaining the analyzers, so I used that path hoping that would of been the fix and still came up short.

So with my issues the questions I have for the community are the following:

When I git clone the Cortex-Analyzers/analyzers (git clone https://github.com/TheHive-Project/Cortex-Analyzer) what is the file path that these items are being stored to?
What is the actual default file path to the cortex analyzers?
In the following command: ( for I in $(find Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip2 install -r $I; done && \
for I in $(find Cortex-Analyzers -name 'requirements.txt'); do sudo -H pip3 install -r $I || true; done)
Where is the variable Cortex-Analyzers being pulled from? I cant seem to find the location?

Thanks in advance for the help!

### Steps to Reproduce
1. Install and Configure Cortex
2. Pull the Cortex-Analyzers repository
3. Configure Cortex to read from the folder where the analyzers are located.
4. Launch a browser and log into Cortex
5. Click on Analyzers

### Possible Solutions
I believe the file path that i am using is not corrected but i didnt specify a path so i been using the default /opt/Cortex-Analzyers/analyzers. I checked this path and none existed.

**Comment by azgss** [comment]
hi
 I have the same problem, did you find a solution?

**Comment by chaimabt55** [comment]
did u find solution
