### ISSUE TITLE
ElasticSearch 7.x support

### ISSUE THREAD

**Issue by crimsoncore** [TheHive-Project/Cortex#258]
it seems cortex can't connect to Elasticsearch 7, not supported yet?
I'm using the docker compose file with works fine, until I change the Elasticsearch image to 7.4.2

**Comment by BrijJhala** [comment]
I am keep asking this question what is future supported stack. no response. 7.x is not supported for cortex based on their documentation.

**Comment by nadouani** [comment]
Hello @BrijJhala thanks for you patience. ES 6 EOL is planed for Nov 2020, You will be covered before that, stay tuned.

**Comment by BrijJhala** [comment]
@nadouani thanks for response. can you please also let us know when will have some heads up. hence we can have plan with our internal QA with elastic operator.
