### ISSUE TITLE
MISP analyzer fails in Cortex docker with Python 3.5

### ISSUE THREAD

**Issue by mrcdb** [TheHive-Project/Cortex#260]
# MISP analyzer fails in the Docker image of Cortex 3.0.1 because of Python version

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | MacOS X
| Cortex version / git hash   | 3.0.1
| Package Type              | Docker
| Browser type & version    | Safari 13.0.5

### Problem Description
The MISP analyzer plugins fails regardless of its configuration because of a syntax error due to the Python version used in the Docker container.
In particular, the Python shebang refers to `python3`, which references the local install of Python 3.5 in the Docker container. The offending syntax (`self.__edited: bool = True`) is available in Python 3.6+.

### Steps to Reproduce
1. Run Cortex 3.0.1 as Docker container `thehiveproject/cortex:3.0.1`
2. Setup a local MISP instance (e.g. via Docker)
3. Configure the MISP Analyzer on Cortex
4. Run a scan for the MISP Analyzer (e.g. for IP address, domain)
5. Check the error log

### Possible Solutions
Update the official Cortex Docker image to Python 3.6, or side-install Python 3.6 alongside Python 3.5 and update the MISP Analyzer shebang.

### Complementary information
Traceback of exception:
```bash
Traceback (most recent call last):
  File "/opt/Cortex-Analyzers/analyzers/MISP/misp.py", line 3, in <module>
    from mispclient import MISPClient, MISPClientError
  File "/opt/Cortex-Analyzers/analyzers/MISP/mispclient.py", line 2, in <module>
    import pymisp
  File "/usr/local/lib/python3.5/dist-packages/pymisp/__init__.py", line 28, in <module>
    from .abstract import AbstractMISP, MISPEncode, pymisp_json_default, MISPTag, Distribution, ThreatLevel, Analysis  # noqa
  File "/usr/local/lib/python3.5/dist-packages/pymisp/abstract.py", line 111
    self.__edited: bool = True  # As we create a new object, we assume it is edited
                 ^
SyntaxError: invalid syntax
```

**Comment by garanews** [comment]
I confirm.
about pymisp: IMPORTANT NOTE: This library will require at least python 3.6 starting the 1st of January 2020. If you have to legacy versions of python, please use PyMISP v2.4.119.1, and consider updating your system(s). Anything released within the last 2 years will do, starting with Ubuntu 18.04.

I updated python in cortex docker image to version 3.8.2 and it works.

**Comment by garanews** [comment]
@nadouani , @To-om any news on this?

**Comment by To-om** [comment]
From Cortex 3.1, docker image doesn't contain analyzers anymore. Analyzers/responders and Cortex  have different life-cycles, the update of analyzers/responders (including their dependencies) should not be correlated to Cortex update. It is recommended to use docker version of analyzers. This can be done by binding docker service docket inside cortex container (run with `-v /var/run/docker.sock:/var/run/docker.sock`)
