### ISSUE TITLE
Allow external authentication on a reverse proxy

### ISSUE THREAD

**Issue by zmaktouf** [TheHive-Project/Cortex#265]
# Allow external authentication on a reverse proxy
The idea is to implement same feature as the one in TheHive [73!](https://github.com/TheHive-Project/elastic4play/issues/73)

This feature allows to delegate authentication to a reverse proxy, in front of the application. The user identity is forwarded using HTTP header.
This feature is enabled by adding auth.method.header = true in application.conf. Then the name of the header must be set by auth.header.name = AUTH_USER

### Request Type
Feature Request

**Comment by To-om** [comment]
Cortex uses the same authentication modules as TheHive. You can add in your application.conf:
```
auth.method.header = true
auth.header.name = AUTH_USER
```
