### ISSUE TITLE
Update Cortex-Analyzers in docker image

### ISSUE THREAD

**Issue by myasn1k** [TheHive-Project/Cortex#281]
### Request Type
Bug

### Problem Description
Cortex-Analyzers in Cortex docker image isn't pulled, so Cortex docker uses old analyzers and responders.

**Comment by JustCodeIt4Head** [comment]
Did you try to Update them?.
Open a Shell with docker exec -u root -t -i CONTAINER_NAME /bin/bash.
In the Container go to /opt/Cortex-Analyzers/
Then execute "git pull".
Worked like a charm for me with the latest Image.

**Comment by myasn1k** [comment]
> Did you try to Update them?.
> Open a Shell with docker exec -u root -t -i CONTAINER_NAME /bin/bash.
> In the Container go to /opt/Cortex-Analyzers/
> Then execute "git pull".
> Worked like a charm for me with the latest Image.
Yes that's what i did, but i thought that it would have been better for example to pull everything during the build of the image, or during the init script.
> I would also recommend to map the /opt/Cortex-Analyzers/ to the Host System, so you don't have to Shell into the Container to Update your Analyzers and keep ur Data after a Restart
Maybe i should do this, thanks!
