### ISSUE TITLE
subnet datatype

### ISSUE THREAD

**Issue by dadokkio** [TheHive-Project/Cortex#295]
### Feature Request
Add the possibility to insert a subnet as observable

### Problem Description
If I need to search all ip in a subnet I need to add all of them manually and manage them separately.
Adding a new type could help mostly if library can use subnets directly and I just need to lookup bad ips in subnet range.

**Comment by mnmnc** [comment]
I think You can add it yourself. Observables are managed by admin of the TheHive instance. On the cortex side, list of observables are generated by dataTypes available in analyzers JSON configuration, so if you have an analyzer that you created you can just add subnet dataType to accepted observable (assuming code that executes is ready to handle it properly). If you want one of existing analyzers to support subnet dataType, I think you would need to code it and make a pull request to cortex analyzers repository, or patch it localy for your instance only.  
I use many `custom` dataTypes with no issues.

**Comment by dadokkio** [comment]
Thanks! I didn't knew it.
