### ISSUE TITLE
Provide way to reload conf file for new API keys without shutdown.

### ISSUE THREAD

**Issue by JohnOmernik** [TheHive-Project/Cortex#3]
# Provide way to reload conf file for new API keys without shutdown.

### Request Type
Feature Request

### Problem Description
Currently, as far as I can tell, if we get a new configuration for analyzers, it requires us to stop and start cortex.  This could cause failures on currently running analysis, that shouldn't have to happen. Instead a mechanism to either check conf every N seconds (configurable) for changes, and if change reload, or manually request reload of config would be helpful to ensure currently running analysis would not be interrupted .

**Comment by saadkadhi** [comment]
Hi @JohnOmernik,

Thank you for your feature request. This is indeed a must-have that we have been thinking about for some time. We will be consider it for the next major version (1.1.0).

**Comment by To-om** [comment]
Playframework doesn't provide any mechanism to reload configuration without restart the application (unless you run application in development mode).
This issue will be fixed when persistence (database) will be added to Cortex.
