### ISSUE TITLE
Sloppy release naming, 3.0.1 Release is not 3.1.0-RC1

### ISSUE THREAD

**Issue by jakubgs** [TheHive-Project/Cortex#310]
You have a release named `3.0.1 Release` that's actually `3.1.0-RC1`:
https://github.com/TheHive-Project/Cortex/releases/tag/3.1.0-RC1

**Comment by jakubgs** [comment]
Also, is there a build of the release candidate available anywhere so I can test it?

I can't find it under https://download.thehive-project.org/ :
```
 > curl -sI 'https://download.thehive-project.org/cortex-3.1.0-RC1.zip'
HTTP/1.1 404 Not Found
```

**Comment by mnmnc** [comment]
@jakubgs check this out: https://github.com/TheHive-Project/Cortex/milestones

**Comment by jakubgs** [comment]
Actually, there is a binary release, just the filename is slightly different:
https://download.thehive-project.org/cortex-3.1.0-RC1-1.zip
But that one has a bug with creating ElasticSearch indices.

**Comment by nadouani** [comment]
Hello @jakubgs thanks for catching the naming issues of the releases on github.

If you have issues with the RC1 please let us know what is the issue, with details, logs so we can fix it.

We are finalising the 3.1.0 stable right now.

I'll close this issue, and feel free to open a new one if you find bugs so we can track them, thanks a lot

**Comment by jakubgs** [comment]
@nadouani Hey, I already talked with Jerome in your Gitter chat and he confirmed that RC1 has issues with creating indices.

I'll wait for `3.1.0` and try setting it up again. Cheers!
