### ISSUE TITLE
Do you support auth with elasticsearch ?

### ISSUE THREAD

**Issue by PakitoSec** [TheHive-Project/Cortex#312]
Hi,

Do you support auth with elasticsearch ?

I got the following error message: 

missing authentication credentials for REST request

I have username and password defined in search application config.

Thanks for your help,

**Comment by PakitoSec** [comment]
I finally found that the problem is the application conf cample.
it should be user and not username

**Comment by Neuro-HSOC** [comment]
I can confirm the issue and the workaround. Created pull request #315 for this.

**Comment by buzzdeee** [comment]
I ran into the same with 3.1.0-1
