### ISSUE TITLE
New analysis docker job always returns json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by SergeyDrachuk** [TheHive-Project/Cortex#313]
### Request Type
Bug 

### Work Environment

| Question                        | Answer
|---------------------------------|--------------------
| OS version (server)        | CentOS Linux release 8.2.2004 (Core)
| OS version (client)          | Linux Mint 19 Tara 
| Cortex version / git hash | Cortex 3.1.0-1
| Package Type                 | Docker
| Browser type & version   | Firefox 82.0.2 (64-bit)

### Problem Description
Analyzers configured as 
`analyzer.urls=["https://download.thehive-project.org/analyzers.json"]`
Any analysis job fails with the same error:
`Traceback (most recent call last):
  File "GoogleDNS/GoogleDNS_resolve.py", line 78, in <module>
    GoogleDNS_resolve().run()
  File "GoogleDNS/GoogleDNS_resolve.py", line 13, in __init__
    Analyzer.__init__(self)
  File "/usr/local/lib/python3.8/site-packages/cortexutils/analyzer.py", line 17, in __init__
    Worker.__init__(self, job_directory)
  File "/usr/local/lib/python3.8/site-packages/cortexutils/worker.py", line 31, in __init__
    self._input = json.load(sys.stdin)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### Steps to Reproduce
1. On Centos 8 use the docker-compose.yml
`version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - /home/es:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    command: --no-config
    volumes: 
       - /etc/cortex/application.conf:/etc/cortex/application.conf
       - /var/run/docker.sock:/var/run/docker.sock
`
2. Start by `docker-compose up`
3. In a browser "Update the database" and create superadmin account "admin". Login under superadmin account "admin". Create organization "O" and add user "a" with password "a". Relogin under account "a". Open Organization page, enable analyser " GoogleDNS_resolve_1_0_0". Press "New Analysis", enter 8.8.8.8 as IP, select " GoogleDNS_resolve_1_0_0" and run analysis.

### Complementary information
There are no warnings in the cortex log.
I've tried GoogleDNS_resolve_1_0_0, AbuseIPDB_1_0, VirusTotal_GetReport_3_0
The following is the corresponding docker-compose log:

`elasticsearch_1  | {"type": "server", "timestamp": "2020-11-04T18:07:08,954Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "b410aeaf5da5", "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[cortex_5][0]]]).", "cluster.uuid": "hNQypQycR1m_HXbyCcGS2g", "node.id": "QGscI4yxSBqQ_HVVPc8ZNQ"  }
cortex_1         | [info] o.t.c.s.JobSrv - Looking for similar job in the last 10 minutes (worker=114ce84e40d4003894f1be99f8e837a6, dataType=ip, data=Left(8.8.8.8), tlp=2, parameters={})
cortex_1         | [info] o.t.c.s.JobSrv - Looking for similar job in the last 10 minutes (worker=6ddbd7b0943c0fe6e8e0b1b9f4b3150e, dataType=ip, data=Left(8.8.8.8), tlp=2, parameters={})
cortex_1         | [info] o.t.c.s.JobSrv - Looking for similar job in the last 10 minutes (worker=bc3314e957b7365a989f004f57e82d40, dataType=ip, data=Left(8.8.8.8), tlp=2, parameters={})
cortex_1         | [info] o.t.c.s.AuditActor - Job sUNylHUBDvXsSkOxtXGe has be updated (JsDefined("InProgress"))
cortex_1         | [info] o.t.c.s.AuditActor - Job sENylHUBDvXsSkOxtXGL has be updated (JsDefined("InProgress"))
cortex_1         | [info] o.t.c.s.AuditActor - Job r0NylHUBDvXsSkOxtXGK has be updated (JsDefined("InProgress"))
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/googledns_resolve:1: ProgressMessage{id=1, status=Pulling from cortexneurons/googledns_resolve, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=3, status=Pulling from cortexneurons/virustotal_getreport, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/googledns_resolve:1: ProgressMessage{id=null, status=Digest: sha256:c95dd3c6bba5a27188cfd8d59481d789fd3e12048c7bbdd0861021a9127bbe61, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/googledns_resolve:1: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/googledns_resolve:1, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=null, status=Digest: sha256:0731d88f0f3f233e2f0521558d8bfd4a48fc42cd35a2f9b860d30bebcd8a7333, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/virustotal_getreport:3, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/abuseipdb:1: ProgressMessage{id=1, status=Pulling from cortexneurons/abuseipdb, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/abuseipdb:1: ProgressMessage{id=null, status=Digest: sha256:9b68d31e9b40e549be2bdddf578ca89137ca6aff29b7f6fafaf929c29cc534f4, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/abuseipdb:1: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/abuseipdb:1, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] o.t.c.s.DockerJobRunnerSrv - Execute container 9ead78667923c5ebfeff6dfce1902cc1e4342930a354051156c8267c17f208cb
cortex_1         |   timeout: 30 minutes
cortex_1         |   image  : cortexneurons/googledns_resolve:1
cortex_1         |   volume : /tmp/cortex-jobs/cortex-job-sUNylHUBDvXsSkOxtXGe-4849523791080341509:/job
cortex_1         | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: 9ead78667923c5ebfeff6dfce1902cc1e4342930a354051156c8267c17f208cb
cortex_1         | [info] o.t.c.s.DockerJobRunnerSrv - Execute container 11d1d8ed6678e25b6f01caf3b0b5596c0ca93b6a8548db935694c0d501eba575
cortex_1         |   timeout: 30 minutes
cortex_1         |   image  : cortexneurons/virustotal_getreport:3
cortex_1         |   volume : /tmp/cortex-jobs/cortex-job-sENylHUBDvXsSkOxtXGL-5858535185901954717:/job
cortex_1         | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: 11d1d8ed6678e25b6f01caf3b0b5596c0ca93b6a8548db935694c0d501eba575
cortex_1         | [info] o.t.c.s.DockerJobRunnerSrv - Execute container d73c49f18b28997caa537ecf3d487607f72dde358c76599bb2989a25a8ecdafb
cortex_1         |   timeout: 30 minutes
cortex_1         |   image  : cortexneurons/abuseipdb:1
cortex_1         |   volume : /tmp/cortex-jobs/cortex-job-r0NylHUBDvXsSkOxtXGK-919106639296589216:/job
cortex_1         | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: d73c49f18b28997caa537ecf3d487607f72dde358c76599bb2989a25a8ecdafb
cortex_1         | [info] o.t.c.s.JobSrv - Job sUNylHUBDvXsSkOxtXGe has finished with status Failure
cortex_1         | [info] o.t.c.s.AuditActor - Job sUNylHUBDvXsSkOxtXGe has be updated (JsDefined("Failure"))
cortex_1         | [info] o.t.c.s.JobSrv - Job sENylHUBDvXsSkOxtXGL has finished with status Failure
cortex_1         | [info] o.t.c.s.AuditActor - Job sENylHUBDvXsSkOxtXGL has be updated (JsDefined("Failure"))
cortex_1         | [info] o.t.c.s.JobSrv - Job r0NylHUBDvXsSkOxtXGK has finished with status Failure
cortex_1         | [info] o.t.c.s.AuditActor - Job r0NylHUBDvXsSkOxtXGK has be updated (JsDefined("Failure"))
`

**Comment by SergeyDrachuk** [comment]
I'm new to a docker. As i understood analysers run in their own containers with all required dependencies.
May be the error can be fixed on my side? 
Is the Cortex 3.1.0-1 stable release? Maybe i should use another one?
Is TheHive-Project/Cortex the right place to create the issue?
I will be thankful for any ideas.

**Comment by senyuuri** [comment]
Hi I've also encountered the same error on every analyzer. I am running Cortex 3.1.0-1 in docker. The host OS is Ubuntu 18.04.1 LTS.

Below is the rrror message in Cortex. Seems the observable value failed to be passed into the analyzer?
```
{
  "errorMessage": "Traceback (most recent call last):\n  File \"Urlscan.io/urlscan_analyzer.py\", line 102, in <module>\n    UrlscanAnalyzer().run()\n  File \"Urlscan.io/urlscan_analyzer.py\", line 8, in __init__\n    Analyzer.__init__(self)\n  File \"/usr/local/lib/python3.8/site-packages/cortexutils/analyzer.py\", line 17, in __init__\n    Worker.__init__(self, job_directory)\n  File \"/usr/local/lib/python3.8/site-packages/cortexutils/worker.py\", line 31, in __init__\n    self._input = json.load(sys.stdin)\n  File \"/usr/local/lib/python3.8/json/__init__.py\", line 293, in load\n    return loads(fp.read(),\n  File \"/usr/local/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n",
  "input": null,
  "success": false
}
```

The Cortex log shows that the analyser container has been pulled, created, then failed
```
cortex_1         | [info] o.t.c.s.AuditActor - Job BtWmo3UBc1LKzn_bIJSO has be updated (JsDefined("InProgress"))
cortex_1         | [info] o.t.c.s.AuditActor - Job B9Wmo3UBc1LKzn_bIJSO has be updated (JsDefined("InProgress"))
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_scan:3: ProgressMessage{id=3, status=Pulling from cortexneurons/virustotal_scan, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_scan:3: ProgressMessage{id=null, status=Digest: sha256:89e72fc25e30bf46e845156e0ef6a6d57dedbab5eabdac353d9a53e17cdd1be7, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_scan:3: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/virustotal_scan:3, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] o.t.c.s.DockerJobRunnerSrv - Execute container bb984b39c4d42638441740f4e06f837b2a2791e03aec2a76b6ba666f9ec05dee
cortex_1         |   timeout: 30 minutes
cortex_1         |   image  : cortexneurons/virustotal_scan:3
cortex_1         |   volume : /tmp/cortex-jobs/cortex-job-BtWmo3UBc1LKzn_bIJSO-1736503124560716016:/job
cortex_1         | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: bb984b39c4d42638441740f4e06f837b2a2791e03aec2a76b6ba666f9ec05dee
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=3, status=Pulling from cortexneurons/virustotal_getreport, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=null, status=Digest: sha256:0731d88f0f3f233e2f0521558d8bfd4a48fc42cd35a2f9b860d30bebcd8a7333, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] c.s.d.c.LoggingPullHandler - pull cortexneurons/virustotal_getreport:3: ProgressMessage{id=null, status=Status: Image is up to date for cortexneurons/virustotal_getreport:3, stream=null, error=null, progress=null, progressDetail=null}
cortex_1         | [info] o.t.c.s.DockerJobRunnerSrv - Execute container 5da3507d560ec89df4524027a12a1f81de5370f93f489e427edca2ff011a3a0c
cortex_1         |   timeout: 30 minutes
cortex_1         |   image  : cortexneurons/virustotal_getreport:3
cortex_1         |   volume : /tmp/cortex-jobs/cortex-job-B9Wmo3UBc1LKzn_bIJSO-8667419531129219663:/job
cortex_1         | [info] c.s.d.c.DefaultDockerClient - Starting container with Id: 5da3507d560ec89df4524027a12a1f81de5370f93f489e427edca2ff011a3a0c
cortex_1         | [info] o.t.c.s.AuditActor - Job BtWmo3UBc1LKzn_bIJSO has be updated (JsDefined("Failure"))
cortex_1         | [info] o.t.c.s.JobSrv - Job BtWmo3UBc1LKzn_bIJSO has finished with status Failure
```

docker-compose file
```
cortex:
    image: thehiveproject/cortex:3.1.0
    depends_on:
      - elasticsearch
    ports:
      - "127.0.0.1:9001:9001"
    command: --job-directory /tmp/cortex-jobs --docker-job-directory /var/run/cortex/jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cortex-jobs:/tmp/cortex-jobs

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - http.host=0.0.0.0
      - cluster.name=hive
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
```

**Comment by mluhta** [comment]
This seems to be a configuration issue, atleast for @SergeyDrachuk . You need to mount a directory (e.g. /tmp/cortex-jobs) in the docker-compose configuration and define the job directories in the ` application.conf ` like this:

```
job {
  timeout = 30 minutes
  runners = [docker]
  directory = "/tmp/cortex-jobs"
  dockerDirectory = "/tmp/cortex-jobs"
}
```

Cortex doesn't seem to currently use the ` --job-directory ` and ` --docker-job-directory ` command line arguments but I got it working with the configuration file.

**Comment by SergeyDrachuk** [comment]
> This seems to be a configuration issue, atleast for @SergeyDrachuk . You need to mount a directory (e.g. /tmp/cortex-jobs) in 
@mluhta, you are the best!
Thank you very much!

Working configs:

#docker-compose.yml
version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - /home/es:/usr/share/elasticsearch/data
  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    command: --no-config
    volumes:
       - /etc/cortex/application.conf:/etc/cortex/application.conf
       - /var/run/docker.sock:/var/run/docker.sock
       - /tmp/cortex-jobs:/tmp/cortex-jobs

#/etc/cortex/application.conf
play.http.secret.key="WmyUst8nBUTRkK2MA1uothTsSblAhjZZt91bnwTyS8gCiY9Wr8KhU2lDNolGUdm8"
search.uri = "http://elasticsearch:9200"
job.directory="/tmp/cortex-jobs"

analyzer.urls=["https://download.thehive-project.org/analyzers.json"]
responder.urls=["https://download.thehive-project.org/responders.json"]

job {
  timeout = 30 minutes
  runners = [docker]
  directory = "/tmp/cortex-jobs"
  dockerDirectory = "/tmp/cortex-jobs"
}
