### ISSUE TITLE
Cannot deserialize ES results after migration to Cortex 3.1

### ISSUE THREAD

**Issue by nicocti** [TheHive-Project/Cortex#323]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)      | Debian Buster
| OS version (client)       | Ubuntu 20.04
| Cortex version / git hash   | 3.1.0
| Package Type              | Docker
| Browser type & version    | Not applicable

### Problem Description

Hello,

I tried to migrate from Cortex 3.0.1 to Cortex 3.1.0, but I'm facing deserialization errors when accessing the UI and trying to authenticate:

`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of 'long' out of START_OBJECT token`

I can confirm that the ES instance is running 7.9.3 and was created in 6.8:

```json
~$ curl -X GET 'http://elasticsearch:9200/cortex_4?pretty'
{
  "cortex_4" : {
    "aliases" : { },
    "mappings" : {
      "date_detection" : false,
      "numeric_detection" : false,
      "properties" : {...}
    },
    "settings" : {
      "index" : {
        "mapping" : {
          "nested_fields" : {
            "limit" : "100"
          }
        },
        "number_of_shards" : "5",
        "provided_name" : "cortex_4",
        "creation_date" : "1595607504954",
        "number_of_replicas" : "1",
        "uuid" : "nENE3MbbTSa1szb3gE83oQ",
        "version" : {
          "created" : "6080099",
          "upgraded" : "7090399"
        }
      }
    }
  }
}
```

### Steps to Reproduce
1. Upgrade from ES 6 to ES7 (two nodes) without reindexing
2. Upgrade from Cortex 3.0.1 to 3.1.0 (docker)
2. Try to log in on the UI

### Complementary information

Any clue ?

**Comment by nicocti** [comment]
Issue on my side. I fixed my ES migration ! Closing ;)

**Comment by 0cta** [comment]
@nicocti Can you elaborate a bit on how you solved the issue? Facing the same problem atm

**Comment by nicocti** [comment]
Hello @0cta ! Sorry I missed your question. Actually I had to manually "upgrade" Cortex database via the UI as I was not automatically redirected to this webpage https://github.com/TheHive-Project/CortexDocs/blob/master/admin/updating.md

The path is `/index.html#!/maintenance` and is not documented AFAIK
