### ISSUE TITLE
Cortexutils Responder

### ISSUE THREAD

**Issue by D4rkw0lv3s** [TheHive-Project/Cortex#326]
# Cortexutils Responder Error

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS 7
| OS version (client)       |  Win10
| Cortex version / git hash   | 3.1.0-1
| Package Type              | Docker
| Browser type & version    | chrome, firefox, edge
| Python Versions | Python 2.7.5 and Python 3.7.9

### Problem Description
When I run the responder it gives me this error for both responders Mailer and PhishFeedback.

`Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/PhishFeedback/phish_feedback.py", line 3, in <module>    from cortexutils.responder import Responder ModuleNotFoundError: No module named 'cortexutils'
`

`Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/Mailer/mailer.py", line 6, in <module>    from cortexutils.responder import Responder ModuleNotFoundError: No module named 'cortexutils'`

### Steps to Reproduce
1. Install and enable PhishFeedback/Mailer
2. Install cortexutils for both python2 and python3
1. Config the responder/s
1. Put the tag "mail:email@myemail.com" or "user_mail:email@myemail.com" in the case with name: Phishing report
2. Add observable with the email and tags, in case the tags don't work.
3. Run the responder
4. Check in Cortex the failed log message

### Possible Solutions
- I tried to add to the compose the site-packages, but it did nothing...

### Complementary information
docker-compose-yml
>version: "3.8"
>services:
>  cortex:
>    image: 'thehiveproject/cortex:3.1.0-1'
>    container_name: cortex
>    restart: unless-stopped
>    volumes:
>      - /containers/cortex01/application.conf:/etc/cortex/application.conf
>      - /var/run/docker.sock:/var/run/docker.sock
>      - /tmp:/tmp
>      - /opt/Cortex-Analyzers/analyzers/:/opt/Cortex-Analyzers/analyzers/
>      - /opt/Cortex-Analyzers/responders/:/opt/Cortex-Analyzers/responders/
>      - /containers/certs/http.p12:/http.p12
>      - /usr/local/lib/python3.7/site-packages/:/usr/local/lib/python3.7/site-packages/
>    ports:
>      - '0.0.0.0:9001:9001'

application.conf
```
# play.http.secret.key="generate_the_secret_key"

## ElasticSearch
search {
  # Name of the index
  index = cortex01

  # ElasticSearch instance address.
  uri = "https://X.X.X.X:9200"

  ...

  ## Authentication configuration
  user = "$user"
  password = "$pass"

  ## SSL configuration
  keyStore {
    path = "/http.p12"
    type = "PKCS12" # or PKCS12
    password = "$pass"
  }
  trustStore {
    path = "/http.p12"
    type = "PKCS12" # or PKCS12
    password = "$pass"
  }
}

## Cache
cache.job = 10 minutes

## Authentication
auth {
        method.basic = true
        provider = [local,ad]
        ad {
                # The Windows domain name in DNS format. This parameter is required if you do not use
                # 'serverNames' below.
                domainFQDN = "X.X.X.X"

                # Optionally you can specify the host names of the domain controllers instead of using 'domainFQDN
                # above. If this parameter is not set, TheHive uses 'domainFQDN'.
                #serverNames = [ad1.mydomain.local, ad2.mydomain.local]

                # The Windows domain name using short format. This parameter is required.
                domainName = "$domain"

                # If 'true', use SSL to connect to the domain controller.
                useSSL = false
        }
...
}

job {
  runner = [docker]
}

# ANALYZERS
analyzer {
  urls = [
    "https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json"
  ]

  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}

# RESPONDERS
responder {
  urls = ["/opt/Cortex-Analyzers/responders"]
  # "https://dl.bintray.com/thehive-project/cortexneurons/responders.json"

  fork-join-executor {
    parallelism-min = 2
    parallelism-factor = 2.0
    parallelism-max = 4
  }
}
```

**Comment by garanews** [comment]
it seems you are using cortex in docker (because you said) and analyzers/responders in docker too (because in conf you have  
```
job {
  runner = [docker]
}
```

In this case no needed to download any python dependencies but url for analyzers/responders must be set to correct url:
```"https://download.thehive-project.org/analyzers.json"```
```"https://download.thehive-project.org/analyzers.json"   ```
 
Otherwise you sould remove job runner docker part and can use the local path of cortex analyzrers mapping repo as you did.

It's like you did a mix between 2 possibilities.
Have a look here, you can find some example: https://github.com/TheHive-Project/Docker-Templates

**Comment by D4rkw0lv3s** [comment]
> it seems you are using cortex in docker (because you said) and analyzers/responders in docker too (because in conf you have
> 
> ```
> job {
>   runner = [docker]
> }
> ```
> 
> In this case no needed to download any python dependencies but url for analyzers/responders must be set to correct url:
> `"https://download.thehive-project.org/analyzers.json"`
> `"https://download.thehive-project.org/analyzers.json" `
> 
> Otherwise you sould remove job runner docker part and can use the local path of cortex analyzrers mapping repo as you did.
> 
> It's like you did a mix between 2 possibilities.
> Have a look here, you can find some example: https://github.com/TheHive-Project/Docker-Templates

Ok, but if i want to use custom made analyzers/responders, and still running this analyzers/responders in docker should I make a docker image for my custom mades or it's better just not run in docker the analyzers/responders and just run locally?

What is the better choice?

**Comment by dadokkio** [comment]
A simple option could be having two different cortex, one local and one docker.. or you could build your local images as docker

**Comment by D4rkw0lv3s** [comment]
I've removed the 
```
job {
  runner = [docker]
}
```

and added the local path 
```
analyzer {
  urls = ["/opt/Cortex-Analyzers/analyzers"]
...
responder {
  urls = ["/opt/Cortex-Analyzers/responders"]
```

And it gives me the same error, when i try to run the responders. But the analyzers work fine.
```
Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/PhishFeedback/phish_feedback.py", line 3, in <module>    from cortexutils.responder import ResponderModuleNotFoundError: No module named 'cortexutils'

Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/Mailer/mailer.py", line 6, in <module>    from cortexutils.responder import ResponderModuleNotFoundError: No module named 'cortexutils'
```

===

Then I added again the
```
job {
  runner = [docker]
}
```

and changed to the url path
```
analyzer {
  urls = [
    "https://dl.bintray.com/thehive-project/cortexneurons/analyzers.json"
  ]
...
responder {
  urls = [
   "https://dl.bintray.com/thehive-project/cortexneurons/responders.json"
  ]
```

The result was the same error for the Mailer (The Phish couldn't test because it's local):
```
Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/Mailer/mailer.py", line 6, in <module>    from cortexutils.responder import ResponderModuleNotFoundError: No module named 'cortexutils'
```

**Comment by D4rkw0lv3s** [comment]
> A simple option could be having two different cortex, one local and one docker.. or you could build your local images as docker
> You can find some info here: https://github.com/TheHive-Project/CortexDocs/blob/master/installation/install-guide.md

But first I need to not have this error in both option :/

**Comment by dadokkio** [comment]
for local run you need to change job section to:
```
job {
  runner = [local]
}
```


For docker can you check with proper analyzer paths?
```
analyzer {
  urls = [
    "https://download.thehive-project.org/analyzers.json"
  ]
  [..]
}
responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
  ]
  [..]
}
```

**Comment by D4rkw0lv3s** [comment]
> for local run you need to change job section to:
> 
> ```
> job {
>   runner = [local]
> }
> ```
> 
> For docker can you check with proper analyzer paths?
> 
> ```
> analyzer {
>   urls = [
>     "https://download.thehive-project.org/analyzers.json"
>   ]
>   [..]
> }
> responder {
>   urls = [
>     "https://download.thehive-project.org/responders.json"
>   ]
>   [..]
> }
> ```

I tried to run the local with the job section mention and the local paths, it gives me the same error.

Then I tried the runner docker with those paths and nothing, same error.

===
More info:

```
# python -m pip install cortexutils

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: cortexutils in /usr/lib/python2.7/site-packages (2.0.0)
```

```
# python3 -m pip install cortexutils

Requirement already satisfied: cortexutils in /usr/local/lib/python3.7/site-packages (2.0.0)

```

**Comment by dadokkio** [comment]
Just to check everything. You have a dockerized cortex with local analyzers, right?

You have installed analyzer/responder requirements inside the cortex docker image?
In my case with docker compose the procedure from a fresh build is something like this:

```
dadokkio@Q# docker-compose exec cortex bash
```

Then in the docker image [where 9d31cd3df80a is the docker image of cortex]
```
root@9d31cd3df80a:/opt/cortex# apt update
root@9d31cd3df80a:/opt/cortex# apt install python3-pip
root@9d31cd3df80a:/opt/cortex# pip3 install cortexutils
```

**Comment by D4rkw0lv3s** [comment]
> pip3 install cortexutils

God bless you!

I didn't know you needed these settings... I didn't see any of that in the documentation. Thanks!
