### ISSUE TITLE
Error when trying to setup TheHive4

### ISSUE THREAD

**Issue by kouta-ZER0** [TheHive-Project/Cortex#357]
I have tried installing via Docker and directly to the host (Ubuntu 18.04) and always get the below error for JaunsGraph

[info] ScalligraphApplication [|] Loading application ...
[info] o.t.s.ScalligraphModule [|] Loading scalligraph module
[info] a.e.s.Slf4jLogger [|] Slf4jLogger started
[info] a.r.a.t.ArteryTcpTransport [|] Remoting started with transport [Artery tcp]; listening on address [akka://application@127.0.0.1:36473] with UID [1712917545338841818]
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - Starting up, Akka version [2.6.10] ...
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - Registered cluster JMX MBean [akka:type=Cluster]
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - Started up successfully
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
[info] a.c.s.SplitBrainResolver [|] SBR started. Config: strategy [KeepMajority], stable-after [20 seconds], down-all-when-unstable [15 seconds], selfUniqueAddress [akka://application@127.0.0.1:36473#1712917545338841818], selfDc [default].
[info] o.r.Reflections [|] Reflections took 297 ms to scan 1 urls, producing 160 keys and 2424 values 
[info] o.t.t.ClusterSetup [|] Initialising cluster
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - Node [akka://application@127.0.0.1:36473] is JOINING itself (with roles [dc-default], version [0.0.0]) and forming new cluster
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - is the new leader among reachable nodes (more leaders may exist)
[info] a.c.Cluster [|] Cluster Node [akka://application@127.0.0.1:36473] - Leader is moving node [akka://application@127.0.0.1:36473] to [Up]
[info] o.t.t.ClusterListener [|] Member is Up: akka://application@127.0.0.1:36473
[info] a.c.s.SplitBrainResolver [|] This node is now the leader responsible for taking SBR decisions among the reachable nodes (more leaders may exist).
[info] a.c.s.ClusterSingletonManager [|] Singleton manager starting singleton actor [akka://application/system/singletonManagerJanusClusterManager/JanusClusterManager]
[info] a.c.s.ClusterSingletonManager [|] ClusterSingletonManager state change [Start -> Oldest]
[info] a.c.s.ClusterSingletonProxy [|] Singleton identified at [akka://application/system/singletonManagerJanusClusterManager/JanusClusterManager]
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (1)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (2)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (3)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (4)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (5)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (6)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (7)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (8)
[warn] o.t.s.u.Retry [|] An error occurs (Could not find implementation class: org.janusgraph.diskstorage.inmemory.InMemoryStoreManager), retrying (9)

**Comment by nadouani** [comment]
This is not a Cortex issue. Closing
