### ISSUE TITLE
Using python virtualenv for analyzers

### ISSUE THREAD

**Issue by trolldbois** [TheHive-Project/Cortex#37]
# Virtualenv support for analyzer: update documentation or add configuration option

### Request Type
Feature request

### Work Environment
Debian, Cortext with systemd

### Problem Description
Cortex analyzer are run using python-in-path.
There is no configuration to specify the python interpreter or virtualenv to use.

### Steps to Reproduce
1. Install analyzers python requirements in a virtualenv /opt/cortex/virtual_env_path
2. Run an analyzer with cortex
3. errors, as cortexutils is not in system python pythonpath

### Possible Solutions
1. Add a hint in documentation to say:
Change systemd cortex.service to include the following in the [Service] section:
```
  # use a cortext virtualenv for analyzer
  Environment=PATH=/opt/cortex/virtual_env_path/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
2. add a configuration in application.conf to handle a virtualenv for analyzers

**Comment by trolldbois** [comment]
Any ETA for a quick mention in the documentation ?

**Comment by To-om** [comment]
Instead of using python virtualenv, next major version of cortex will support Docker. Then you will be able to use any version of Python.
