### ISSUE TITLE
Cortex standalone installation to test in university project?

### ISSUE THREAD

**Issue by aliidrees695** [TheHive-Project/Cortex#420]
Cortex Stand alone testing for University Project as student 

Can I install cortex alone on my laptop and test the analyzers to write the paper? if yes how I will take the input to analyze?

**Comment by jeromeleonard** [comment]
yes you can, we have docker images, DEB and RPM packages. to run tests on analyzers, please refer to the Developer guides on this site: https://thehive-project.github.io/Cortex-Analyzers/
