### ISSUE TITLE
Error when clicking out of the "New Analysis" box

### ISSUE THREAD

**Issue by benmeyer50** [TheHive-Project/Cortex#48]
# Error when clicking out of the "New Analysis" box

### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       |  Win 7
| Cortex version / git hash   | 1.1.4, hash of the commit
| Package Type              | Binary
| Browser type & version    | Chrome 61

### Problem Description
When clicking out of the "New Analysis" box the following error appears in the bottom right corner
![image](https://user-images.githubusercontent.com/1085904/32677226-977edc82-c62b-11e7-888f-8606fcbaddd0.png)

### Steps to Reproduce
1. Click "New Analysis" on header bar
2. Once information box pops up click anywhere else on the browser window to make it go away
3. Error pops up in corner

**Comment by saadkadhi** [comment]
Hi @benmeyer50. This is very unusual. I've never had such an error. Can you provide excerpts from your logfile please (`/var/log/cortex/application.log` by default)?

**Comment by benmeyer50** [comment]
Hi @saadkadhi. Nothing is actually showing in that specific log file. I replicated the issue a couple times this morning and still nothing seems to be generated.

**Comment by nadouani** [comment]
Can you take a look to the browser's console? If the backend logs don't show anything, the only way to understand what happened is to check the client side errors :(

This is definitely an unexpected error, so we need more context.

Thanks

**Comment by nadouani** [comment]
Well, I took a look on it, it seems to be a very minor issue on the front end side, nothing blocking, but irritating :)

We will fix it on the next release.

Thanks
