### ISSUE TITLE
File_Info issue

### ISSUE THREAD

**Issue by dolfan70** [TheHive-Project/Cortex#53]
### Request Type

Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | RedHat 6.9
| OS version (client)       | N/A
| Cortex version / git hash   | 1.1.4
| Package Type              | RPM
| Browser type & version    | N/A

### Problem Description
Analyzer File_Info erroring out processing a file
### Steps to Reproduce
1.Opened up file_info analyzer on the cortex
2. Selected TLP:White Data Type:File then put a file with a sample trojan inside.
3.{
  "errorMessage": "Unexpected Error: 'module' object has no attribute 'hash_file'",
  "input": {
    "tlp": 0,
    "dataType": "file",
    "content-type": "application/pdf",
    "filename": "secured document.pdf",
    "file": "/tmp/cortex-4878520860249705835-datafile",
    "config": {
      "max_tlp": 3,
      "check_tlp": false,
      "service": ""
    }
  },
  "success": false
}

**Comment by saadkadhi** [comment]
@dolfan70 are you able to share the sample so we can reproduce the issue? If so, you can put it in a password-protected zip file and send it to us at support@thehive-project.org. If the file is available on VT, send us its hash and we'll grab it from there.

In the future, please open analyzer-related issued in the [corresponding repository](https://github.com/CERT-BDF/Cortex-Analyzers/issues/new).

**Comment by mrod42** [comment]
[Samples.zip](https://github.com/CERT-BDF/Cortex/files/1572805/Samples.zip)

The password is [infected]

**Comment by saadkadhi** [comment]
Thanks @mrod42. @jeromeleonard would you please look into this at your earliest opportunity? Thanks.

**Comment by nadouani** [comment]
This is obsolete, since File Info analyzer have bee nrewritten
