### ISSUE TITLE
Application.conf doesn't have Yeti config nor allows for API Auth

### ISSUE THREAD

**Issue by darksheer** [TheHive-Project/Cortex#54]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | OS X
| Cortex version / git hash   | latest
| Package Type              | Binary (Debian Package)
| Browser type & version    | N/A

### Problem Description
The Yeti analyzer doesn't have the default config in the application.conf

The Yeti analyzer doesn't allow for configuration of an API key.  By default, Yeti is configured with NO auth.  By deleting the default Yeti user, access to the UI / API requires an API key. The analyzer should be configured to allow API level access via token auth. 

### Steps to Reproduce
1. Install Yeti
2. Create a new user in Yeti
3. Generate a new API key for the new Yeti users
4. Delete the default Yeti user. 

### Possible Solutions
Have a config sysntax in the /etc/cortex/application.conf that provides:
1. URL to the Yeti Server
2. API Key for the Yet API

**Comment by hackdefendr** [comment]
This seems to work for me.

> Yeti {
>       # URL of the Yeti server: example: http://120.0.0.1:5000
>       url = "http://x.x.x.x"
>       key = 'xxxxxxxxxxxxxx'
> }

**Comment by saadkadhi** [comment]
@darksheer I will close this issue for now as @hackdefendr provided a potential solution. Feel free to reopen it if needed.
