### ISSUE TITLE
Yara Analyzer Fails with Invalid Field Name

### ISSUE THREAD

**Issue by darksheer** [TheHive-Project/Cortex#56]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.0.4. LTS
| OS version (client)       | OS X
| Cortex version / git hash   | Latest
| Package Type              | Debian Package
| Browser type & version    | N/A

### Problem Description
Executing the Yara analyzer, with the suggested repo in the applications.conf file errors with:

```
{
  "errorMessage": "Error: Invalid output\nTraceback (most recent call last):\n  File \"./yara_analyzer.py\", line 72, in <module>\n    YaraAnalyzer().run()\n  File \"./yara_analyzer.py\", line 31, in __init__\n    self.ruleset.append(yara.compile(rulepath + '/index.yar'))\nyara.SyntaxError: ./malware/RANSOM_BadRabbit.yar(35): invalid field name \"imphash\"\n",
  "input": null,
  "success": false
}
```

### Steps to Reproduce
1. Install cortex
2. Download the Yara repo defined in the /etc/cortex/application.conf
3 Specific the directory and index.yar file
4. Execute the analyzer against a file
5. Error returned

### Possible Solutions
Probably needs some more graceful error checking in case the maintainers of those Yara files write something that is 'bad'.

**Comment by saadkadhi** [comment]
@darksheer do you still have this issue with Cortex 2.0.4 and the latest batch of analyzers?
