### ISSUE TITLE
Shodan Analyzer Fails - Missing API key

### ISSUE THREAD

**Issue by axpatito** [TheHive-Project/Cortex#59]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS Linux release 7.4.1708 (Core)
| OS version (client)       | 10
| Cortex version / git hash   | cortex.noarch 1.1.4-1                      @thehive-project
| Package Type              | YUM
| Browser type & version    | 

### Problem Description
Shodan API key is not being read by the application. I'm receving the following error:

{
  "errorMessage": "Missing Shodan API key",
  "input": {
    "tlp": 0,
    "dataType": "domain",
    "data": "[DOMAIN.COM]", #covered
    "config": {
      "max_tlp": 1,
      "check_tlp": true,
      "service": "search"
    }
  },
  "success": false
}

Config in /etc/cortex/application.conf

shodan {
      apikey = "vVKXXXXXXXXXXXXXXXXXXXXXXk7Az"
    }

### Complementary information
I can't start debugging the .py files directly. I can't get a file written with the read API key because the code does not seem to by able to reach the __init__ method for the ShodaAnalyzer class.

**Comment by nadouani** [comment]
Hello, the property names on the configuration file are case sensitive, so please make sure you use the right case for the *shodan* key.

**Comment by nadouani** [comment]
In fact, it should be Shodan based on the docs: https://github.com/TheHive-Project/CortexDocs/blob/master/analyzer_requirements.md#shodan

**Comment by axpatito** [comment]
thanks for the reply @nadouani. I made the adjustment and still receive the same error. Can you provide a valid config? I'm using the default config provided on the file (Which was undercase).

**Comment by nadouani** [comment]
Well, the docs link provided above should be fine, just restart your cortex instance to make sure the config is talen into account.

If the problem still exist, please share your config (hide private keys and creds)

**Comment by axpatito** [comment]
Great! So I got it running. The default config for Shodan in my package is found under misp modules. I moved it to the analyzer.config dictionary and it worked. Maybe it would be a good idea to move the default value?
