### ISSUE TITLE
Unable for Cortex to connected to MISP

### ISSUE THREAD

**Issue by shaykster** [TheHive-Project/Cortex#61]
Unable for Cortex to connected to MISP

### Work Environment

TheHive 3.0.3
Elastic4Play 1.4.2
Play 2.6.7
Elastic4s 5.6.0
ElasticSearch 5.6.2
MISP
CORTEX LOCAL CORTEX - 1.1.4 (OK)

There are no guidelines on how to troubleshoot. All configuration on config files have been performed as per documents.

**Comment by nadouani** [comment]
Looks like you mean: "Unable for TheHive to connect to MISP", not Cortex, right?

**Comment by shaykster** [comment]
Yes that’s right - sorry meant TheHive

**Comment by shaykster** [comment]
Can you provide guideline on troubleshooting - all configs steps have been followed

**Comment by nadouani** [comment]
I'm afraid we could not say more than what has been said on https://github.com/TheHive-Project/TheHiveDocs/blob/master/admin/configuration.md#7-misp

But if you share your config, I can probably tell you where is the issue? Or if you have error logs in /var/log/thehive/thehive.log
