### ISSUE TITLE
PAP as an analyzer restriction

### ISSUE THREAD

**Issue by iglocska** [TheHive-Project/Cortex#65]
Using TLP to automatically restrict analyzers is an excellent idea. Maybe something to extend it with in a similar fashion could be PAP (https://github.com/MISP/misp-taxonomies/blob/master/PAP/machinetag.json).

To cross-reference it, we'll try to mimic the functionality for misp-modules and tie it into MISP: (https://github.com/MISP/MISP/issues/3045)

**Comment by derDuffy** [comment]
I absolutely second that !
