### ISSUE TITLE
Unable to disable analyzers

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex#72]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16
| Cortex version / git hash   | 2
| Package Type              | DEB
| Browser type & version    | Chrome 65

### Problem Description
Cannot disable analyzers once enabled

### Steps to Reproduce
1. Enable an analyzer
2. Click disable
3. Acknowledge the warning, click through
4. Get error that you cannot delete the analyzer

### Complementary information
![image](https://user-images.githubusercontent.com/20773170/38206127-324d8982-3677-11e8-9fe6-a6271a7362c3.png)

**Comment by saadkadhi** [comment]
Thx for reporting this @robertnixon2003. We will look into it and if confirmed we'll fix it in the next hotfix.
