### ISSUE TITLE
libexec/activator-launch-1.3.10.jar missing

### ISSUE THREAD

**Issue by stdio-h** [TheHive-Project/Cortex#74]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| Cortex version / git hash   | 605f76179e8427f8e1d0691d8f004ba7569ff5d2
| Package Type              | From source
| Browser type & version    | n/a

### Problem Description
libexec/activator-launch-1.3.10.jar is missing

```
bin/activator clean stage
Could not find launcher jar: /home/thehive/Cortex/libexec/activator-launch-1.3.10.jar
```

### Steps to Reproduce
1. git clone https://github.com/TheHive-Project/Cortex.git 
1. cd Cortex
1. bin/activator clean stage
Could not find launcher jar: /home/user/Cortex/libexec/activator-launch-1.3.10.jar

**Comment by To-om** [comment]
Hi,
Activator has been deprecated and will be removed. Please use `./sbt` instead of `bin/activator`.

**Comment by To-om** [comment]
Documentation has been updated.
