### ISSUE TITLE
Silently failure when ElasticSearch is unreachable

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/Cortex#76]
### Request Type
Bug

### Work Environment
Cortex 2.0.1

### Problem Description
If ElasticSearch is not started, Cortex web interface shows an empty page, without any error message.

### Complementary information
If ElasticSearch is unreachable, Cortex back-end returns the following error on any requests that need ES:
```
500 Internal Server Error

{"type":"NoNodeAvailable","message":"ElasticSearch cluster is unreachable"}
```

**Comment by liuxuehao** [comment]
Now I have the same problem, when I pull the image in docker and run it. Access it via google browser, prompting ‘’Error: ElasticSearch cluster is unreachable ’’
Ubuntu 16.04.3
Docker 19.03.1
Cortex: 3.0.0-RC4
Elasticsearch: 6.8.0
