### ISSUE TITLE
I know I can't delete a user within the GUI, but what if I delete the entire 'cortex' Elasticsearch index?

### ISSUE THREAD

**Issue by juanchristian** [TheHive-Project/Cortex#78]
### Request Type
Question

Is there a way to delete the entire Cortex database just to get over with the users "table"? I created my user inside the default "cortex" organization, but now I found out that I need it inside my created company to work with the analyzers, but sadly I can't use the same username because it was used already.

Not being able to delete a user is terrible and I don't really now what's the advantage for that. Is this a hindrance from Elasticsearch or a design choice by Cortex?

**Comment by nadouani** [comment]
You can delete it from the ES directly

```
curl -XDELETE http://localhost:9200/cortex_1/user/LOGIN 
```

- **LOGIN** is your username
- **hxxp://localhost:9200** is your elasticsarch
