### ISSUE TITLE
Change of global config for proxy is not reflected in analyzer's configurations

### ISSUE THREAD

**Issue by racco42** [TheHive-Project/Cortex#81]
### Request Type
Enhancement

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server       | Fedora 27
| OS version (client)       | Win7
| Cortex version / git hash   | 2.0.2
| Package Type              | RPM
| Browser type & version    | 

### Problem Description
When global configuration for proxy is changed, it is not reflected in individual analyzer's configurations. The configuration in the analyzer gets "copy" of the global setting, but there is no way to say "use global". Changing the global config then requires changing all analyzer's configs.

### Steps to Reproduce
1. Set global proxy to "something"
2. Set analyzer config with suggested proxy settings (copy from global) 
3. Change the global proxy to "something2"
4. Look into analyzer configuration

### Possible Solutions
Introduce "use global" checkbox for proxy settings in analyzer config. May also be valid for any future global config value.

**Comment by nadouani** [comment]
![screen shot 2018-04-06 at 11 26 28](https://user-images.githubusercontent.com/21827/38414204-169968ae-398e-11e8-8746-a12244b07155.png)
