### ISSUE TITLE
Display existing analyzers with invalid definition

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex#82]
### Request Type
Feature Request

### Problem Description
The **Analyzers** tab under organization details page list all the available and valid analyzers. By valid we mean, analyzers that still exist and appliable to at least one datatype.

But an organization could end up having invalid analyzers (ex: after an analyzer version bump, where old analyzer is not longer valid). The actual version of Cortex doesn't allow org admins to delete such analyzers.

The goal of this feature is to display the invalid analyzers and allow admins to delete them.

**Comment by alisp7** [comment]
hi 
i am new to using thehive and after installation and creating an alert i wanted to run analyzers it return this error  "Sorry, there are currently no analyzers for the selected observable type(s) " and when i moved to Available analyzer configurations tab there is only : 
![Capture3](https://user-images.githubusercontent.com/35430014/120067119-c751fd80-c02e-11eb-9c30-2dcf22120649.PNG)

and i analyzer tab there ware multi invalid analyzer : 
![Capture4](https://user-images.githubusercontent.com/35430014/120067164-0b450280-c02f-11eb-8175-9b62576a73d9.PNG)

how can i fix this problem ?

**Comment by azgss** [comment]
@alisp7 hello 
I found the same problem, did you find a solution?
