### ISSUE TITLE
Allow specifying a cache period per analyzer

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/Cortex#85]
### Request Type
Feature Request

### Problem Description
In Cortex 2 we have introduced the concept of cache when running analyzers. The case is configurable from the `application.conf` file and is global to all analyzers.

This issues aims to make the cache customizable, per analyzer, from the UI.

**Comment by BrijJhala** [comment]
@nadouani how can we clean cache when api key is changed ? it still picking up from cache even after i changed api key.

**Comment by nadouani** [comment]
Which API key are you referring to? the User's API key or the analyzer's one?

**Comment by BrijJhala** [comment]
@nadouani , when analyzer API key is changed. it still fetching from cache. ideally it should clear. Based on codebase cacheTag hash is checking data, type, workerId etc.ideally it should to have api key in hash too. thank you
