### ISSUE TITLE
Allow arbitrary parameters for a job

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/Cortex#86]
### Request Type
Feature Request

### Work Environment
Cortex 2.0.2

### Problem Description
When submitting job, parameters can be set but they are merged with configuration and must be declared in analyzer definition file (json file). The aim of this issue is to permit to send arbitrary parameters to an analyzer. Parameters will not be merged with configuration anymore but added in new "parameters" key. Parameters must be a JSON object.

With the job request:
```
{
  "data": "127.0.0.1",
  "dataType": "ip",
  "tlp": 2,
  "message": "here",
  "parameters": {
    "param1": "value1",
    "param2": "value2",
  }
}
```
the analyzer will receive:
```
{
  "data": "127.0.0.1",
  "dataType": "ip",
  "tlp": 2,
  "message": "here",
  "config": { ... },
  "parameters": {
    "param1": "value1",
    "param2": "value2",
  }
}
```

**Comment by janwychowaniak** [comment]
Hello.
Is there any possibility to make use of this parameters section for jobs started from TheHive? How I can set them for observables created in TheHive, preferably with using its API?
What I want to accomplish is to find a way to pass arbitrary information via TheHive API all the way through to a custom Cortex analyzer I wrote.
Thanks.
