### ISSUE TITLE
Bug with Configuration of Cortex Analyzers in UI of Base Config not Showing up

### ISSUE THREAD

**Issue by gertz27** [TheHive-Project/Cortex#99]
### Request Type
Bug 

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | Windows 8
| Cortex version             | 2.0.4
| Package Type              | RPM

### Problem Description
After modifying the json files for some custom cortex analyzers so that the baseConfigs and configurationItems were set up, there would not be a row for that specific base config on the UI. 

### Steps to Reproduce
1. Add custom Cortex analyzer to analyzers folder
2. Modify json files of analyzers to contain same baseConfig value and configurationItems
3. Restart cortex
4. Go to UI to configure analyzers
5. Base config value does not appear under Configurations

**Comment by saadkadhi** [comment]
@gertz27 can you provide sample files corresponding to your custom analyzers please? Please ensure to anonymize any sensitive data they may contain. If you prefer you can send them over to us by email at support@. 

We need to be able to look at them to try to reproduce the problem on our side. Otherwise, we can't help much.

**Comment by nadouani** [comment]
There is for sure an error on the JSON file you have cooked to describe the configs. Please share it

**Comment by nadouani** [comment]
Well, I think Cortex might don't like the `type: int` of the `port` config item. It should be `number` instead of `int`.

Don't you have errors on the console regarding the parsing of this config?

**Comment by gertz27** [comment]
Thank you! I have not been receiving or seeing any errors on the console or any of our logs for this, but this has fixed the issue I was having.
